backend:
  name: git-gateway
  branch: v8

media_folder: _site/img/uploads
public_folder: /img/uploads

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Content, name: body, widget: markdown}
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Content, name: body, widget: markdown}
  - name: homepage
    label: Homepage
    files:
      - label: Homepage
        name: homepage
        file: src/content/homepage.md
        fields:
          - { label: Lede, name: lede, widget: string }
